[package]
name = "idb-core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
serde = { version = "1", features = ["derive"] }
parking_lot = "0.12"
shuttle = { version = "0.9.1", optional = true }

[dev-dependencies]
bincode = "1"

[features]
shuttle = ["dep:shuttle"]

[lints.clippy]
all = "warn"
